/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class Engine */

#ifndef _Included_Engine
#define _Included_Engine
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     Engine
 * Method:    getBestMove
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_Engine_getBestMove
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
