# =========================================================
# Default Engine Configuration
# =========================================================

[search]
delta_prune_threshold      = 1000
see_prune_threshold        = -50

aspiration_window          = 50
aspiration_start_depth     = 6
aspiration_depth_scale     = 10
aspiration_research_scale  = 2.0

draw_eval                  = 0
contempt                   = 0

r_nmp                      = 3
r_lmr_const                = 0.99
r_lmr_denom                = 3.14

lmr_move_order_threshold   = 3
lmr_depth_threshold        = 2


[options]
quiescence        = true
aspiration        = true
delta_pruning     = true
see_pruning       = true
move_ordering     = true
mvvlva_ordering   = false
see_ordering      = true

uci_show_wdl      = false
nnue              = true


[scores]
tt_base        = 10000000
pv_base        = 9000000
promo_base     = 8500000
good_cap_base  = 8000000
killer_base    = 7000000
quiet_base     = 0
bad_cap_base   = -1000000


[engine]
magics            = true
move_overhead_ms  = 30
max_threads       = 1
hash_size_mb      = 512
pondering         = false

nnue_weight_path  = bin/nnue_wgts/768_128x2.bin
opening_book_path = bin/Titans.bin
syzygy_path       = bin/